# Generated by Django 6.0.5 on 2026-05-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("artist", models.CharField(max_length=200)),
                ("release_date", models.DateField()),
                ("cover_url", models.URLField(blank=True)),
                ("genre", models.CharField(blank=True, max_length=100)),
                ("label", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
