# Generated by Django 6.0.5 on 2026-06-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="reviewer_type",
            field=models.CharField(
                choices=[("critic", "乐评人"), ("user", "用户")], max_length=10
            ),
        ),
    ]
