# Generated by Django 6.0.5 on 2026-06-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_reviewer_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="content",
        ),
        migrations.RemoveField(
            model_name="review",
            name="reviewer_type",
        ),
        migrations.AddField(
            model_name="album",
            name="critic_review",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="album",
            name="critic_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
