# Generated by Django 6.0.5 on 2026-06-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_remove_review_content_remove_review_reviewer_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="critic_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="乐评人姓名"
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="critic_published_at",
            field=models.DateField(blank=True, null=True, verbose_name="乐评发布时间"),
        ),
    ]
