# Generated by Django 6.0.5 on 2026-06-26 13:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_album_critic_name_album_critic_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="critic_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="album",
            name="critic_published_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="critic_score",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.RenameModel(
            old_name="Review",
            new_name="UserRating",
        ),
        migrations.AlterField(
            model_name="userrating",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="reviews.album",
            ),
        ),
    ]
