# Generated by Django 6.0.5 on 2026-09-01 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0006_alter_album_critic_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrating",
            name="score",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
    ]
