# Generated by Django 6.0.5 on 2026-09-19 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0008_userrating_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userrating",
            constraint=models.UniqueConstraint(
                fields=("album", "user"), name="unique_user_album_rating"
            ),
        ),
    ]
